# -*- coding: utf-8 -*-
#
# Sysystems Administration for Cyborgs build configuration file.
#
# This file is execfile()d with the current directory set to its containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys
import os

from giza.config.runtime import RuntimeStateConfig
from giza.config.helper import fetch_config

conf = fetch_config(RuntimeStateConfig())
sconf = conf.system.files.data.sphinx_local

# -- General configuration -----------------------------------------------------

extensions = ['sphinx.ext.todo', 'alabaster']
templates_path = [os.path.join(conf.paths.projectroot, 'templates'),
                  os.path.join(conf.paths.projectroot, conf.paths.buildsystem, 'templates')]
source_suffix = '.txt'
master_doc = 'contents'

project = u'Systems Administration for Cyborgs'
copyright = u'2012, Sam Kleinman and Contributors'

version = ''
release = '1'

exclude_patterns = []

pygments_style = 'sphinx'
intersphinx_mapping = {'http://docs.python.org/': None}

# -- Options for HTML output ---------------------------------------------------

import alabaster

rst_epilog = ".. |commit| replace:: ``{0}``".format(conf.git.commit)

fontawesome_link_cdn = True
html_use_smartypants = True
html_theme = sconf.theme.name
html_theme_path = [ os.path.join(conf.paths.output, 'institute-tools', 'themes'), alabaster.get_path() ]

html_static_path = ['./source/.static']

html_title = sconf.theme.sitename
html_short_title = "Cyborg Systems"

html_logo = None
html_favicon = None

html_theme_options = {
    'analytics_id': sconf.theme.google_analytics,
    'github_user': 'cyborgisntitute',
    'github_repo': 'administration',
    'github_button': True,
}

html_sidebars = sconf.sidebars

#html_title = None
#html_short_title = None
#html_logo = None
#html_favicon = None

html_use_index = True
html_show_sourcelink = False
html_show_sphinx = False
html_show_copyright = True
htmlhelp_basename = 'cyborg-institute'

# -- Options for LaTeX output --------------------------------------------------

latex_paper_size = 'letter'
latex_font_size = '10pt'

latex_documents = []

if 'pdfs' in conf.system.files.data:
    for pdf in conf.system.files.data.pdfs:
        latex_documents.append((pdf.source, pdf.output, pdf.title, pdf.author, pdf.doc_class))


#latex_use_parts = False
latex_show_pagerefs = True
latex_show_urls = False

#latex_logo = None
#latex_preamble = ''
#latex_appendices = []
latex_domain_indices = False

# -- Options for Epub output ---------------------------------------------------

epub_title = sconf.theme.sitename
epub_author = u'Sam Kleinman'
epub_publisher = u'Sam Kleinman'
epub_copyright = u'2012, Sam Kleinman'

epub_tocdepth = 1
epub_tocdup = False

epub_scheme = 'URL'
epub_identifier = conf.project.url

#epub_uid = ''
#epub_pre_files = []
#epub_post_files = []
#epub_exclude_files = []
